{
 "title": "Qujata Analysis",
 "description": "A simple overview of the most important Docker host and container metrics. (cAdvisor/Prometheus) updated from ID 893 by Thibaut Mottet",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "iPerf metrics - Time evolution",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "parser": "backend",
     "root_selector": "intervals",
     "source": "url",
     "type": "json",
     "url": "http://172.20.0.48:30100/metrics.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "iPerf metrics - CPU utilization",
   "type": "table",
   "description": "Shows detailed metrics corresponding to cpu utilization",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "parser": "backend",
     "root_selector": "end",
     "source": "url",
     "type": "json",
     "url": "http://172.20.0.48:30100/metrics.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "iPerf metrics - Sent",
   "type": "table",
   "description": "Shows detailed metrics corresponding to iPerf sent petitions",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "parser": "backend",
     "root_selector": "end",
     "source": "url",
     "type": "json",
     "url": "http://172.20.0.48:30100/metrics.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "iPerf metrics - Received",
   "type": "table",
   "description": "Shows detailed metrics corresponding to iPerf received petitions",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "parser": "backend",
     "root_selector": "end",
     "source": "url",
     "type": "json",
     "url": "http://172.20.0.48:30100/metrics.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "SecGW1 Total bytes received",
   "type": "timeseries",
   "description": "SecGW1 Total bytes received",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=\"secgw1\"}[15s])) by (name) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SecGW2 Total bytes received",
   "type": "timeseries",
   "description": "SecGW2 Total bytes received",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=\"secgw2\"}[15s])) by (name) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SecGW1 CPU (%)",
   "type": "timeseries",
   "description": "SecGW1 CPU",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=\"secgw1\"}[15s])) by (name) ",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "SecGW2 CPU (%)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=\"secgw2\"}[15s])) by (name) ",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "SecGW1 Memory",
   "type": "timeseries",
   "description": "SecGW1 Memory",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_memory_usage_bytes{name=\"secgw1\"}[15s])) by (name) ",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "SecGW2 Memory",
   "type": "timeseries",
   "description": "SecGW2 Memory",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_memory_usage_bytes{name=\"secgw2\"}[15s])) by (name) ",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}